-- date형 타입을 string으로 반환 (날짜)
create or replace FUNCTION UF_GET_DATE(V_DATETIME IN DATE) RETURN VARCHAR2 AS 
BEGIN
  RETURN TO_CHAR(V_DATETIME, 'YYYY-MM-DD');
END UF_GET_DATE;

-- date형 타입을 string으로 반환 (시간)
CREATE OR REPLACE FUNCTION UF_GET_TIME(V_DATETIME IN DATE) RETURN VARCHAR2 AS 
BEGIN
  RETURN TO_CHAR(V_DATETIME, 'HH24:MI:SS');
END UF_GET_TIME;