conn /as sysdba

create tablespace kh_scheduler datafile 'C:\oraclexe\app\oracle\oradata\XE\KH_SCHEDULER.DBF' size 100m autoextend on next 10m;

create user dytpq identified by 123123 default tablespace kh_scheduler;
grant resource, connect, dba to dytpq;

-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- USER_AUTH Table Create SQL
CREATE TABLE USER_AUTH
(
    ID      VARCHAR2(20)    NOT NULL, 
    AUTH    NUMBER(1)       DEFAULT 1 NOT NULL, 
    CONSTRAINT USER_AUTH_PK PRIMARY KEY (ID)
)
;

COMMENT ON TABLE USER_AUTH IS '회원 권한 테이블'
;

COMMENT ON COLUMN USER_AUTH.ID IS '아이디'
;

COMMENT ON COLUMN USER_AUTH.AUTH IS '0:탈퇴, 1:일반'
;


-- SCHEDULE Table Create SQL
CREATE TABLE SCHEDULE
(
    SC_IDX            NUMBER          NOT NULL, 
    SC_TITLE          VARCHAR2(20)    NOT NULL, 
    ID                VARCHAR2(20)    NOT NULL, 
    SC_PLACE          VARCHAR2(20)    NULL, 
    SC_START          DATE            NOT NULL, 
    SC_END            DATE            NOT NULL, 
    SC_ALL_DAY        CHAR(1)         DEFAULT 'N' NOT NULL, 
    SC_CONTENT        CLOB            NULL, 
    SC_REG_DATE       DATE            DEFAULT SYSDATE NOT NULL, 
    SC_MODIFY_DATE    DATE            NULL, 
    SC_FAVORITE       CHAR(1)         DEFAULT 'N' NOT NULL, 
    SC_USALBE         CHAR(1)         DEFAULT 'Y' NOT NULL, 
    CONSTRAINT SCHEDULE_PK PRIMARY KEY (SC_IDX)
)
;

COMMENT ON TABLE SCHEDULE IS '일정 목록'
;

COMMENT ON COLUMN SCHEDULE.SC_IDX IS '인덱스'
;

COMMENT ON COLUMN SCHEDULE.SC_TITLE IS '제목'
;

COMMENT ON COLUMN SCHEDULE.ID IS '아이디'
;

COMMENT ON COLUMN SCHEDULE.SC_PLACE IS '장소'
;

COMMENT ON COLUMN SCHEDULE.SC_START IS '시작일시'
;

COMMENT ON COLUMN SCHEDULE.SC_END IS '종료일시'
;

COMMENT ON COLUMN SCHEDULE.SC_ALL_DAY IS '하루종일여부'
;

COMMENT ON COLUMN SCHEDULE.SC_CONTENT IS '내용'
;

COMMENT ON COLUMN SCHEDULE.SC_REG_DATE IS '작성일'
;

COMMENT ON COLUMN SCHEDULE.SC_MODIFY_DATE IS '마지막 수정일'
;

COMMENT ON COLUMN SCHEDULE.SC_FAVORITE IS '즐겨찾기'
;

COMMENT ON COLUMN SCHEDULE.SC_USALBE IS '일정 사용 여부'
;

ALTER TABLE SCHEDULE
    ADD CONSTRAINT FK_SCHEDULE_ID_USER_AUTH_ID FOREIGN KEY (ID)
        REFERENCES USER_AUTH (ID)
;


-- USER_INFO Table Create SQL
CREATE TABLE USER_INFO
(
    ID          VARCHAR2(20)    NOT NULL, 
    PWD         VARCHAR2(20)    NOT NULL, 
    NAME        VARCHAR2(20)    NOT NULL, 
    PHONE       VARCHAR2(20)    NOT NULL, 
    EMAIL       VARCHAR2(30)    NOT NULL, 
    REG_DATE    DATE            DEFAULT SYSDATE NOT NULL, 
    CONSTRAINT USER_INFO_PK PRIMARY KEY (ID)
)
;

COMMENT ON TABLE USER_INFO IS '회원 테이블'
;

COMMENT ON COLUMN USER_INFO.ID IS '아이디'
;

COMMENT ON COLUMN USER_INFO.PWD IS '비밀번호'
;

COMMENT ON COLUMN USER_INFO.NAME IS '이름'
;

COMMENT ON COLUMN USER_INFO.PHONE IS '핸드폰번호'
;

COMMENT ON COLUMN USER_INFO.EMAIL IS '이메일'
;

COMMENT ON COLUMN USER_INFO.REG_DATE IS '가입일'
;

ALTER TABLE USER_INFO
    ADD CONSTRAINT FK_USER_INFO_ID_USER_AUTH_ID FOREIGN KEY (ID)
        REFERENCES USER_AUTH (ID)
;

ALTER TABLE USER_INFO
    ADD CONSTRAINT UC_EMAIL UNIQUE (EMAIL)
;


-- HOLIDAY Table Create SQL
CREATE TABLE HOLIDAY
(
    H_DATE    DATE            NOT NULL, 
    H_NAME    VARCHAR2(20)    NOT NULL, 
    CONSTRAINT HOLIDAY_PK PRIMARY KEY (H_DATE)
)
;

COMMENT ON TABLE HOLIDAY IS '달력 정보'
;

COMMENT ON COLUMN HOLIDAY.H_DATE IS '공휴일날짜'
;

COMMENT ON COLUMN HOLIDAY.H_NAME IS '공휴일명'
;


-- DIARY Table Create SQL
CREATE TABLE DIARY
(
    D_IDX            NUMBER          NOT NULL, 
    D_TITLE          VARCHAR2(20)    NOT NULL, 
    ID               VARCHAR2(20)    NOT NULL, 
    D_CONTENT        CLOB            NOT NULL, 
    D_REG_DATE       DATE            DEFAULT SYSDATE NOT NULL, 
    D_MODIFY_DATE    DATE            NULL, 
    D_FAVORITE       CHAR(1)         DEFAULT 'N' NOT NULL, 
    CONSTRAINT DIARY_PK PRIMARY KEY (D_IDX)
)
;

COMMENT ON TABLE DIARY IS '다이어리'
;

COMMENT ON COLUMN DIARY.D_IDX IS '인덱스'
;

COMMENT ON COLUMN DIARY.D_TITLE IS '제목'
;

COMMENT ON COLUMN DIARY.ID IS '아이디'
;

COMMENT ON COLUMN DIARY.D_CONTENT IS '내용'
;

COMMENT ON COLUMN DIARY.D_REG_DATE IS '작성일'
;

COMMENT ON COLUMN DIARY.D_MODIFY_DATE IS '마지막 수정일'
;

COMMENT ON COLUMN DIARY.D_FAVORITE IS '즐겨찾기'
;

ALTER TABLE DIARY
    ADD CONSTRAINT FK_DIARY_ID_USER_AUTH_ID FOREIGN KEY (ID)
        REFERENCES USER_AUTH (ID)
;


-- GALLERY Table Create SQL
CREATE TABLE GALLERY
(
    G_IDX            NUMBER           NOT NULL, 
    G_TITLE          VARCHAR2(20)     NOT NULL, 
    ID               VARCHAR2(20)     NOT NULL, 
    G_CONTENT        CLOB             NULL, 
    G_PHOTO1         VARCHAR2(200)    NOT NULL, 
    G_PHOTO2         VARCHAR2(200)    NULL, 
    G_PHOTO3         VARCHAR2(200)    NULL, 
    G_REG_DATE       DATE             DEFAULT SYSDATE NOT NULL, 
    G_MODIFY_DATE    DATE             NULL, 
    G_FAVORITE       CHAR(1)          DEFAULT 'N' NOT NULL, 
    CONSTRAINT GALLERY_PK PRIMARY KEY (G_IDX)
)
;

COMMENT ON TABLE GALLERY IS '갤러리'
;

COMMENT ON COLUMN GALLERY.G_IDX IS '인덱스'
;

COMMENT ON COLUMN GALLERY.G_TITLE IS '제목'
;

COMMENT ON COLUMN GALLERY.ID IS '아이디'
;

COMMENT ON COLUMN GALLERY.G_CONTENT IS '내용'
;

COMMENT ON COLUMN GALLERY.G_PHOTO1 IS '사진1'
;

COMMENT ON COLUMN GALLERY.G_PHOTO2 IS '사진2'
;

COMMENT ON COLUMN GALLERY.G_PHOTO3 IS '사진3'
;

COMMENT ON COLUMN GALLERY.G_REG_DATE IS '작성일'
;

COMMENT ON COLUMN GALLERY.G_MODIFY_DATE IS '마지막 수정일'
;

COMMENT ON COLUMN GALLERY.G_FAVORITE IS '즐겨찾기'
;

ALTER TABLE GALLERY
    ADD CONSTRAINT FK_GALLERY_ID_USER_AUTH_ID FOREIGN KEY (ID)
        REFERENCES USER_AUTH (ID)
;


-- SCHEDULE_INVITED_USER Table Create SQL
CREATE TABLE SCHEDULE_INVITED_USER
(
    SI_IDX    NUMBER          NOT NULL, 
    SC_IDX    NUMBER          NOT NULL, 
    ID        VARCHAR2(20)    NOT NULL, 
    CONSTRAINT SCHEDULE_INVITED_USER_PK PRIMARY KEY (SI_IDX)
)
;

COMMENT ON TABLE SCHEDULE_INVITED_USER IS '일정 초대 회원'
;

COMMENT ON COLUMN SCHEDULE_INVITED_USER.SI_IDX IS '인덱스'
;

COMMENT ON COLUMN SCHEDULE_INVITED_USER.SC_IDX IS '스케쥴 인덱스'
;

COMMENT ON COLUMN SCHEDULE_INVITED_USER.ID IS '아이디'
;

ALTER TABLE SCHEDULE_INVITED_USER
    ADD CONSTRAINT FK_SCHEDULE_INVITED_USER_SC_ID FOREIGN KEY (SC_IDX)
        REFERENCES SCHEDULE (SC_IDX)
;


-- ALARM Table Create SQL
CREATE TABLE ALARM
(
    AL_IDX      NUMBER     NOT NULL, 
    SC_IDX      NUMBER     NOT NULL, 
    AL_TIMER    NUMBER     NOT NULL, 
    AL_RE       CHAR(1)    DEFAULT 'Y' NOT NULL, 
    CONSTRAINT ALARM_PK PRIMARY KEY (AL_IDX)
)
;

COMMENT ON TABLE ALARM IS '알림 테이블'
;

COMMENT ON COLUMN ALARM.AL_IDX IS '인덱스'
;

COMMENT ON COLUMN ALARM.SC_IDX IS '스케쥴 인덱스'
;

COMMENT ON COLUMN ALARM.AL_TIMER IS '알림 시간 설정'
;

COMMENT ON COLUMN ALARM.AL_RE IS '알림 반복 여부'
;

ALTER TABLE ALARM
    ADD CONSTRAINT FK_ALARM_SC_IDX_SCHEDULE_SC_ID FOREIGN KEY (SC_IDX)
        REFERENCES SCHEDULE (SC_IDX)
;

CREATE OR REPLACE VIEW USER_VW AS
SELECT * FROM USER_AUTH AU LEFT OUTER JOIN USER_INFO UI USING (ID);

alter table schedule modify (sc_title varchar2(50));
ALTER TABLE SCHEDULE RENAME COLUMN SC_USALBE TO SC_USABLE;


create sequence alarm_seq;
create sequence schedule_invited_user_seq;
create sequence diary_seq;

ALTER TABLE SCHEDULE_INVITED_USER ADD CONSTRAINT FK_SCHEDULE_INVITED_USER_ID FOREIGN KEY(ID) REFERENCES USER_AUTH(ID);

create sequence gallery_seq;

